name: aniboard
version: '1.0-BETA'
main: site.anihaven.aniboard.Aniboard
api-version: '1.21'

depend: []
softdepend: [PlaceholderAPI, Vault]

commands:
  aniboard:
    description: Toggle scoreboard display
    aliases: [ab, scoreboard]
    permission: aniboard.use
    permission-message: "&cYou don't have permission to use this command!"

permissions:
  aniboard.use:
    description: Allows players to toggle their scoreboard
    default: true
  aniboard.reload:
    description: Allows reloading the plugin configuration
    default: op
  aniboard.admin:
    description: Administrative permissions for AniBoard
    default: op
    children:
      aniboard.reload: true
      aniboard.use: true