# AniBoard Configuration
# Use ยง for legacy color codes (e.g., ยงa, ยงc, ยง6)
# Use & for legacy color codes (e.g., &a, &c, &6) - works with LuckPerms/Vault
# Use <#FF00FF> for hex colors
# Use " " (space in quotes) for blank lines

# Multiple scoreboard layouts - add as many as you want!
layouts:
  default:
    title: "ยง6ยงlAni<#FFD700>ยงlBoard"
    lines:
      - " "
      - "ยง7Welcome <#00FFFF>%player_name%ยง7!"
      - "ยง7Rank: %vault_prefix%"
      - "ยง7Balance: ยงa$%vault_eco_balance_fixed%"
      - " "
      - "ยง7Health: ยงc%player_health%ยง7/ยงc%player_max_health%"
      - "ยง7Level: <#00BFFF>%player_level%"
      - " "
      - "ยง7Players Online: ยงe%server_online%ยง7/ยงe%server_max%"
      - "ยง7Server: <#FF69B4>mcserver.com"
      - " "

#  pvp:
#    title: "ยงcยงlPvP <#FF0000>ยงlArena"
#    lines:
#      - " "
#      - "ยงcโ ยง7Player: <#FF6B6B>%player_name%"
#      - "ยง7Kills: ยงa%statistic_player_kills%"
#      - "ยง7Deaths: ยงc%statistic_deaths%"
#      - "ยง7K/D: ยงe%statistic_kill_death_ratio%"
#      - " "
#      - "ยง7Health: ยงcโค %player_health%ยง7/ยงc%player_max_health%"
#      - "ยง7Food: ยง6๐ %player_food%ยง7/20"
#      - " "
#      - "ยง7Online: ยงb%server_online% ยง7fighters"
#      - " "

#  survival:
#    title: "ยง2ยงlSurvival <#228B22>World"
#    lines:
#      - " "
#      - "ยง7Explorer: <#90EE90>%player_name%"
#      - "ยง7Rank: %vault_prefix%"
#      - "ยง7Money: ยงa$%vault_eco_balance_fixed%"
#      - " "
#      - "ยง7Level: ยงbโญ %player_level% ยง7(ยงb%player_exp_to_level%ยง7)"
#      - "ยง7World: ยงe%player_world%"
#      - "ยง7Location: ยง7%player_x%ยง8, ยง7%player_y%ยง8, ยง7%player_z%"
#      - " "
#      - "ยง7Players: ยงe%server_online%ยง7/ยงe%server_max%"
#      - " "
#
#  minigames:
#    title: "ยงdยงlMini<#FF1493>Games"
#    lines:
#      - " "
#      - "ยงd๐ฎ ยง7Player: <#FF69B4>%player_name%"
#      - "ยง7Wins: ยงa%statistic_games_won%"
#      - "ยง7Losses: ยงc%statistic_games_lost%"
#      - "ยง7Win Rate: ยงe%statistic_win_rate%%"
#      - " "
#      - "ยง7Current Game: ยงb%current_game%"
#      - "ยง7Game Time: ยง6%game_timer%"
#      - " "
#      - "ยง7Online: ยงe%server_online% ยง7players"
#      - " "

# Settings
settings:
  # How often to update the scoreboard (in seconds)
  update-interval: 1

  # Should the scoreboard be enabled by default for new players?
  enabled-by-default: true

  # Should the scoreboard automatically enable when a player joins?
  auto-enable-on-join: true

  # Default layout to use when players first join or toggle without specifying
  default-layout: "default"

  # Allow players to switch between layouts (if false, only admins can)
  allow-layout-switching: true

# Color codes reference:
# Legacy (ยง or &):
# ยง0/&0 = Black        ยง8/&8 = Dark Gray
# ยง1/&1 = Dark Blue    ยง9/&9 = Blue
# ยง2/&2 = Dark Green   ยงa/&a = Green
# ยง3/&3 = Dark Aqua    ยงb/&b = Aqua
# ยง4/&4 = Dark Red     ยงc/&c = Red
# ยง5/&5 = Dark Purple  ยงd/&d = Light Purple
# ยง6/&6 = Gold         ยงe/&e = Yellow
# ยง7/&7 = Gray         ยงf/&f = White
# ยงl/&l = Bold         ยงo/&o = Italic
# ยงn/&n = Underline    ยงm/&m = Strikethrough
# ยงk/&k = Magic        ยงr/&r = Reset
#
# Hex colors: <#RRGGBB>
# Examples:
# <#FF0000> = Red
# <#00FF00> = Green
# <#0000FF> = Blue
# <#FFD700> = Gold
# <#FF69B4> = Hot Pink
# <#00FFFF> = Cyan